// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package categorydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryHasActiveMovementsForUser = `-- name: CategoryHasActiveMovementsForUser :one
SELECT EXISTS (
  SELECT 1
  FROM movements m
  WHERE m.user_id = $1
    AND m.category_id = $2
    AND m.deleted_at IS NULL
)
`

type CategoryHasActiveMovementsForUserParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) CategoryHasActiveMovementsForUser(ctx context.Context, arg CategoryHasActiveMovementsForUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryHasActiveMovementsForUser, arg.UserID, arg.CategoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteUserCategory = `-- name: DeleteUserCategory :execrows
UPDATE user_categories uc
SET
  deleted_at = $1,
  updated_at = $2
WHERE uc.user_id = $3
  AND uc.category_id = $4
  AND uc.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM movements m
    WHERE m.user_id = $3
      AND m.category_id = $4
      AND m.deleted_at IS NULL
  )
`

type DeleteUserCategoryParams struct {
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
}

func (q *Queries) DeleteUserCategory(ctx context.Context, arg DeleteUserCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserCategory,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.CategoryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserCategoryByUserIDAndCategoryID = `-- name: GetUserCategoryByUserIDAndCategoryID :one
SELECT
  user_id,
  category_id,
  created_at,
  updated_at,
  deleted_at
FROM user_categories
WHERE user_id = $1
  AND category_id = $2
`

type GetUserCategoryByUserIDAndCategoryIDParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) GetUserCategoryByUserIDAndCategoryID(ctx context.Context, arg GetUserCategoryByUserIDAndCategoryIDParams) (UserCategory, error) {
	row := q.db.QueryRow(ctx, getUserCategoryByUserIDAndCategoryID, arg.UserID, arg.CategoryID)
	var i UserCategory
	err := row.Scan(
		&i.UserID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCategoriesByUserIDAfter = `-- name: ListCategoriesByUserIDAfter :many
SELECT
  uc.category_id AS id,
  c.name,
  uc.user_id,
  uc.created_at,
  uc.updated_at
FROM user_categories uc
INNER JOIN categories c
  ON c.id = uc.category_id
 AND c.deleted_at IS NULL
WHERE uc.user_id = $1
  AND uc.deleted_at IS NULL
  AND (
    $2::timestamptz IS NULL
    OR (uc.created_at, uc.category_id) < (
      $2::timestamptz,
      $3::uuid
    )
  )
  AND ($4::text IS NULL OR c.name ILIKE '%' || $4 || '%')
ORDER BY uc.created_at DESC, uc.category_id DESC
LIMIT $5
`

type ListCategoriesByUserIDAfterParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorCategoryID pgtype.UUID        `json:"cursor_category_id"`
	Name             pgtype.Text        `json:"name"`
	LimitCount       int32              `json:"limit_count"`
}

type ListCategoriesByUserIDAfterRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCategoriesByUserIDAfter(ctx context.Context, arg ListCategoriesByUserIDAfterParams) ([]ListCategoriesByUserIDAfterRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesByUserIDAfter,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorCategoryID,
		arg.Name,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesByUserIDAfterRow{}
	for rows.Next() {
		var i ListCategoriesByUserIDAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByUserIDBefore = `-- name: ListCategoriesByUserIDBefore :many
SELECT
  uc.category_id AS id,
  c.name,
  uc.user_id,
  uc.created_at,
  uc.updated_at
FROM user_categories uc
INNER JOIN categories c
  ON c.id = uc.category_id
 AND c.deleted_at IS NULL
WHERE uc.user_id = $1
  AND uc.deleted_at IS NULL
  AND (
    $2::timestamptz IS NULL
    OR (uc.created_at, uc.category_id) > (
      $2::timestamptz,
      $3::uuid
    )
  )
  AND ($4::text IS NULL OR c.name ILIKE '%' || $4 || '%')
ORDER BY uc.created_at ASC, uc.category_id ASC
LIMIT $5
`

type ListCategoriesByUserIDBeforeParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorCategoryID pgtype.UUID        `json:"cursor_category_id"`
	Name             pgtype.Text        `json:"name"`
	LimitCount       int32              `json:"limit_count"`
}

type ListCategoriesByUserIDBeforeRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCategoriesByUserIDBefore(ctx context.Context, arg ListCategoriesByUserIDBeforeParams) ([]ListCategoriesByUserIDBeforeRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesByUserIDBefore,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorCategoryID,
		arg.Name,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesByUserIDBeforeRow{}
	for rows.Next() {
		var i ListCategoriesByUserIDBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCategoryByName = `-- name: UpsertCategoryByName :one
INSERT INTO categories (
  id,
  name,
  created_at,
  updated_at,
  deleted_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
ON CONFLICT (name) DO UPDATE
SET
  deleted_at = NULL
RETURNING id, name
`

type UpsertCategoryByNameParams struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type UpsertCategoryByNameRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpsertCategoryByName(ctx context.Context, arg UpsertCategoryByNameParams) (UpsertCategoryByNameRow, error) {
	row := q.db.QueryRow(ctx, upsertCategoryByName,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i UpsertCategoryByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const upsertUserCategory = `-- name: UpsertUserCategory :one
INSERT INTO user_categories (
  user_id,
  category_id,
  created_at,
  updated_at,
  deleted_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
ON CONFLICT (user_id, category_id) DO UPDATE
SET
  updated_at = CASE
    WHEN user_categories.deleted_at IS NULL THEN user_categories.updated_at
    ELSE EXCLUDED.updated_at
  END,
  deleted_at = NULL
RETURNING user_id, category_id, created_at, updated_at
`

type UpsertUserCategoryParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type UpsertUserCategoryRow struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertUserCategory(ctx context.Context, arg UpsertUserCategoryParams) (UpsertUserCategoryRow, error) {
	row := q.db.QueryRow(ctx, upsertUserCategory,
		arg.UserID,
		arg.CategoryID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i UpsertUserCategoryRow
	err := row.Scan(
		&i.UserID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
