// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: references.sql

package categorydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userExists = `-- name: UserExists :one
SELECT EXISTS (
  SELECT 1
  FROM users
  WHERE id = $1
    AND deleted_at IS NULL
)
`

func (q *Queries) UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
