// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movements.sql

package movementdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMovement = `-- name: CreateMovement :exec
INSERT INTO movements (
  id,
  amount,
  description,
  movement_type_id,
  category_id,
  account_id,
  user_id,
  created_at,
  updated_at,
  deleted_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateMovementParams struct {
	ID             pgtype.UUID        `json:"id"`
	Amount         pgtype.Numeric     `json:"amount"`
	Description    string             `json:"description"`
	MovementTypeID pgtype.UUID        `json:"movement_type_id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateMovement(ctx context.Context, arg CreateMovementParams) error {
	_, err := q.db.Exec(ctx, createMovement,
		arg.ID,
		arg.Amount,
		arg.Description,
		arg.MovementTypeID,
		arg.CategoryID,
		arg.AccountID,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const deleteMovement = `-- name: DeleteMovement :execrows
UPDATE movements
SET
  deleted_at = $2,
  updated_at = $3
WHERE id = $1
  AND deleted_at IS NULL
`

type DeleteMovementParams struct {
	ID        pgtype.UUID        `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeleteMovement(ctx context.Context, arg DeleteMovementParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMovement, arg.ID, arg.DeletedAt, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMovementByID = `-- name: GetMovementByID :one
SELECT
  m.id,
  m.amount,
  m.description,
  m.movement_type_id,
  m.category_id,
  m.account_id,
  m.user_id,
  m.created_at,
  m.updated_at,
  m.deleted_at
FROM movements m
WHERE m.id = $1
  AND m.deleted_at IS NULL
`

func (q *Queries) GetMovementByID(ctx context.Context, id pgtype.UUID) (Movement, error) {
	row := q.db.QueryRow(ctx, getMovementByID, id)
	var i Movement
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Description,
		&i.MovementTypeID,
		&i.CategoryID,
		&i.AccountID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMovementDetailsByIDForUser = `-- name: GetMovementDetailsByIDForUser :one
WITH base AS (
  SELECT
    m.id,
    m.amount,
    m.description,
    m.movement_type_id,
    m.category_id,
    m.account_id,
    m.user_id,
    m.created_at,
    m.updated_at,
    m.deleted_at
  FROM movements m
  WHERE m.id = $1
    AND m.user_id = $2
    AND m.deleted_at IS NULL
)
SELECT
  base.id,
  base.amount,
  base.description,
  base.movement_type_id,
  base.category_id,
  base.account_id,
  base.user_id,
  base.created_at,
  base.updated_at,
  base.deleted_at,
  mt.key AS movement_type_key,
  mt.name AS movement_type_name,
  c.name AS category_name,
  c.is_system AS category_is_system,
  c.system_key AS category_system_key,
  a.name AS account_name
FROM base
INNER JOIN movement_types mt
  ON mt.id = base.movement_type_id
 AND mt.deleted_at IS NULL
INNER JOIN categories c
  ON c.id = base.category_id
 AND c.deleted_at IS NULL
INNER JOIN accounts a
  ON a.id = base.account_id
 AND a.deleted_at IS NULL
`

type GetMovementDetailsByIDForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetMovementDetailsByIDForUserRow struct {
	ID                pgtype.UUID        `json:"id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Description       string             `json:"description"`
	MovementTypeID    pgtype.UUID        `json:"movement_type_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	MovementTypeKey   string             `json:"movement_type_key"`
	MovementTypeName  string             `json:"movement_type_name"`
	CategoryName      string             `json:"category_name"`
	CategoryIsSystem  bool               `json:"category_is_system"`
	CategorySystemKey pgtype.Text        `json:"category_system_key"`
	AccountName       string             `json:"account_name"`
}

func (q *Queries) GetMovementDetailsByIDForUser(ctx context.Context, arg GetMovementDetailsByIDForUserParams) (GetMovementDetailsByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getMovementDetailsByIDForUser, arg.ID, arg.UserID)
	var i GetMovementDetailsByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Description,
		&i.MovementTypeID,
		&i.CategoryID,
		&i.AccountID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MovementTypeKey,
		&i.MovementTypeName,
		&i.CategoryName,
		&i.CategoryIsSystem,
		&i.CategorySystemKey,
		&i.AccountName,
	)
	return i, err
}

const getMovementStatsOverviewByUserID = `-- name: GetMovementStatsOverviewByUserID :one
WITH filtered AS (
  SELECT
    m.amount,
    mt.key AS movement_type_key
  FROM movements m
  INNER JOIN movement_types mt
    ON mt.id = m.movement_type_id
   AND mt.deleted_at IS NULL
  INNER JOIN categories c
    ON c.id = m.category_id
   AND c.deleted_at IS NULL
  INNER JOIN accounts a
    ON a.id = m.account_id
   AND a.deleted_at IS NULL
  WHERE m.user_id = $1
    AND m.deleted_at IS NULL
    AND (
      $2::uuid IS NULL
      OR m.account_id = $2::uuid
    )
    AND (
      $3::uuid IS NULL
      OR m.category_id = $3::uuid
    )
    AND (
      $4::uuid IS NULL
      OR m.movement_type_id = $4::uuid
    )
    AND (
      $5::timestamptz IS NULL
      OR m.created_at >= $5::timestamptz
    )
    AND (
      $6::timestamptz IS NULL
      OR m.created_at <= $6::timestamptz
    )
)
SELECT
  COUNT(*)::bigint AS total_movements,
  COUNT(*) FILTER (WHERE movement_type_key = 'income')::bigint AS income_count,
  COUNT(*) FILTER (WHERE movement_type_key = 'expense')::bigint AS expense_count,
  COALESCE(SUM(amount) FILTER (WHERE movement_type_key = 'income'), 0)::numeric AS income_total,
  COALESCE(SUM(amount) FILTER (WHERE movement_type_key = 'expense'), 0)::numeric AS expense_total,
  COALESCE(SUM(CASE
    WHEN movement_type_key = 'income' THEN amount
    WHEN movement_type_key = 'expense' THEN -amount
    ELSE 0
  END), 0)::numeric AS net_total
FROM filtered
`

type GetMovementStatsOverviewByUserIDParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	MovementTypeID pgtype.UUID        `json:"movement_type_id"`
	DateFrom       pgtype.Timestamptz `json:"date_from"`
	DateTo         pgtype.Timestamptz `json:"date_to"`
}

type GetMovementStatsOverviewByUserIDRow struct {
	TotalMovements int64          `json:"total_movements"`
	IncomeCount    int64          `json:"income_count"`
	ExpenseCount   int64          `json:"expense_count"`
	IncomeTotal    pgtype.Numeric `json:"income_total"`
	ExpenseTotal   pgtype.Numeric `json:"expense_total"`
	NetTotal       pgtype.Numeric `json:"net_total"`
}

func (q *Queries) GetMovementStatsOverviewByUserID(ctx context.Context, arg GetMovementStatsOverviewByUserIDParams) (GetMovementStatsOverviewByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getMovementStatsOverviewByUserID,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.MovementTypeID,
		arg.DateFrom,
		arg.DateTo,
	)
	var i GetMovementStatsOverviewByUserIDRow
	err := row.Scan(
		&i.TotalMovements,
		&i.IncomeCount,
		&i.ExpenseCount,
		&i.IncomeTotal,
		&i.ExpenseTotal,
		&i.NetTotal,
	)
	return i, err
}

const listMovementStatsByAccountByUserID = `-- name: ListMovementStatsByAccountByUserID :many
WITH filtered AS (
  SELECT
    a.id AS account_id,
    a.name AS account_name,
    m.amount,
    mt.key AS movement_type_key
  FROM movements m
  INNER JOIN movement_types mt
    ON mt.id = m.movement_type_id
   AND mt.deleted_at IS NULL
  INNER JOIN categories c
    ON c.id = m.category_id
   AND c.deleted_at IS NULL
  INNER JOIN accounts a
    ON a.id = m.account_id
   AND a.deleted_at IS NULL
  WHERE m.user_id = $1
    AND m.deleted_at IS NULL
    AND (
      $2::uuid IS NULL
      OR m.account_id = $2::uuid
    )
    AND (
      $3::uuid IS NULL
      OR m.category_id = $3::uuid
    )
    AND (
      $4::uuid IS NULL
      OR m.movement_type_id = $4::uuid
    )
    AND (
      $5::timestamptz IS NULL
      OR m.created_at >= $5::timestamptz
    )
    AND (
      $6::timestamptz IS NULL
      OR m.created_at <= $6::timestamptz
    )
)
SELECT
  account_id,
  account_name,
  COUNT(*)::bigint AS movement_count,
  COUNT(*) FILTER (WHERE movement_type_key = 'income')::bigint AS income_count,
  COUNT(*) FILTER (WHERE movement_type_key = 'expense')::bigint AS expense_count,
  COALESCE(SUM(amount) FILTER (WHERE movement_type_key = 'income'), 0)::numeric AS income_total,
  COALESCE(SUM(amount) FILTER (WHERE movement_type_key = 'expense'), 0)::numeric AS expense_total,
  COALESCE(SUM(CASE
    WHEN movement_type_key = 'income' THEN amount
    WHEN movement_type_key = 'expense' THEN -amount
    ELSE 0
  END), 0)::numeric AS net_total
FROM filtered
GROUP BY account_id, account_name
ORDER BY expense_total DESC, movement_count DESC, account_name ASC
`

type ListMovementStatsByAccountByUserIDParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	MovementTypeID pgtype.UUID        `json:"movement_type_id"`
	DateFrom       pgtype.Timestamptz `json:"date_from"`
	DateTo         pgtype.Timestamptz `json:"date_to"`
}

type ListMovementStatsByAccountByUserIDRow struct {
	AccountID     pgtype.UUID    `json:"account_id"`
	AccountName   string         `json:"account_name"`
	MovementCount int64          `json:"movement_count"`
	IncomeCount   int64          `json:"income_count"`
	ExpenseCount  int64          `json:"expense_count"`
	IncomeTotal   pgtype.Numeric `json:"income_total"`
	ExpenseTotal  pgtype.Numeric `json:"expense_total"`
	NetTotal      pgtype.Numeric `json:"net_total"`
}

func (q *Queries) ListMovementStatsByAccountByUserID(ctx context.Context, arg ListMovementStatsByAccountByUserIDParams) ([]ListMovementStatsByAccountByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listMovementStatsByAccountByUserID,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.MovementTypeID,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementStatsByAccountByUserIDRow{}
	for rows.Next() {
		var i ListMovementStatsByAccountByUserIDRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountName,
			&i.MovementCount,
			&i.IncomeCount,
			&i.ExpenseCount,
			&i.IncomeTotal,
			&i.ExpenseTotal,
			&i.NetTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementStatsByCategoryByUserID = `-- name: ListMovementStatsByCategoryByUserID :many
WITH filtered AS (
  SELECT
    c.id AS category_id,
    c.name AS category_name,
    c.is_system AS category_is_system,
    c.system_key AS category_system_key,
    m.amount,
    mt.key AS movement_type_key
  FROM movements m
  INNER JOIN movement_types mt
    ON mt.id = m.movement_type_id
   AND mt.deleted_at IS NULL
  INNER JOIN categories c
    ON c.id = m.category_id
   AND c.deleted_at IS NULL
  INNER JOIN accounts a
    ON a.id = m.account_id
   AND a.deleted_at IS NULL
  WHERE m.user_id = $1
    AND m.deleted_at IS NULL
    AND (
      $2::uuid IS NULL
      OR m.account_id = $2::uuid
    )
    AND (
      $3::uuid IS NULL
      OR m.category_id = $3::uuid
    )
    AND (
      $4::uuid IS NULL
      OR m.movement_type_id = $4::uuid
    )
    AND (
      $5::timestamptz IS NULL
      OR m.created_at >= $5::timestamptz
    )
    AND (
      $6::timestamptz IS NULL
      OR m.created_at <= $6::timestamptz
    )
)
SELECT
  category_id,
  category_name,
  category_is_system,
  category_system_key,
  COUNT(*)::bigint AS movement_count,
  COUNT(*) FILTER (WHERE movement_type_key = 'income')::bigint AS income_count,
  COUNT(*) FILTER (WHERE movement_type_key = 'expense')::bigint AS expense_count,
  COALESCE(SUM(amount) FILTER (WHERE movement_type_key = 'income'), 0)::numeric AS income_total,
  COALESCE(SUM(amount) FILTER (WHERE movement_type_key = 'expense'), 0)::numeric AS expense_total,
  COALESCE(SUM(CASE
    WHEN movement_type_key = 'income' THEN amount
    WHEN movement_type_key = 'expense' THEN -amount
    ELSE 0
  END), 0)::numeric AS net_total
FROM filtered
GROUP BY category_id, category_name, category_is_system, category_system_key
ORDER BY expense_total DESC, movement_count DESC, category_name ASC
`

type ListMovementStatsByCategoryByUserIDParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	MovementTypeID pgtype.UUID        `json:"movement_type_id"`
	DateFrom       pgtype.Timestamptz `json:"date_from"`
	DateTo         pgtype.Timestamptz `json:"date_to"`
}

type ListMovementStatsByCategoryByUserIDRow struct {
	CategoryID        pgtype.UUID    `json:"category_id"`
	CategoryName      string         `json:"category_name"`
	CategoryIsSystem  bool           `json:"category_is_system"`
	CategorySystemKey pgtype.Text    `json:"category_system_key"`
	MovementCount     int64          `json:"movement_count"`
	IncomeCount       int64          `json:"income_count"`
	ExpenseCount      int64          `json:"expense_count"`
	IncomeTotal       pgtype.Numeric `json:"income_total"`
	ExpenseTotal      pgtype.Numeric `json:"expense_total"`
	NetTotal          pgtype.Numeric `json:"net_total"`
}

func (q *Queries) ListMovementStatsByCategoryByUserID(ctx context.Context, arg ListMovementStatsByCategoryByUserIDParams) ([]ListMovementStatsByCategoryByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listMovementStatsByCategoryByUserID,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.MovementTypeID,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementStatsByCategoryByUserIDRow{}
	for rows.Next() {
		var i ListMovementStatsByCategoryByUserIDRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.CategorySystemKey,
			&i.MovementCount,
			&i.IncomeCount,
			&i.ExpenseCount,
			&i.IncomeTotal,
			&i.ExpenseTotal,
			&i.NetTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByUserIDAfter = `-- name: ListMovementsByUserIDAfter :many
WITH base AS (
  SELECT
    m.id,
    m.amount,
    m.description,
    m.movement_type_id,
    m.category_id,
    m.account_id,
    m.user_id,
    m.created_at,
    m.updated_at,
    m.deleted_at
  FROM movements m
  WHERE m.user_id = $1
    AND m.deleted_at IS NULL
    AND (
      $2::timestamptz IS NULL
      OR m.created_at >= $2::timestamptz
    )
    AND (
      $3::timestamptz IS NULL
      OR m.created_at <= $3::timestamptz
    )
    AND (
      $4::timestamptz IS NULL
      OR (m.created_at, m.id) < (
        $4::timestamptz,
        $5::uuid
      )
    )
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT $6
)
SELECT
  base.id,
  base.amount,
  base.description,
  base.movement_type_id,
  base.category_id,
  base.account_id,
  base.user_id,
  base.created_at,
  base.updated_at,
  base.deleted_at,
  mt.key AS movement_type_key,
  mt.name AS movement_type_name,
  c.name AS category_name,
  c.is_system AS category_is_system,
  c.system_key AS category_system_key,
  a.name AS account_name
FROM base
INNER JOIN movement_types mt
  ON mt.id = base.movement_type_id
 AND mt.deleted_at IS NULL
INNER JOIN categories c
  ON c.id = base.category_id
 AND c.deleted_at IS NULL
INNER JOIN accounts a
  ON a.id = base.account_id
 AND a.deleted_at IS NULL
ORDER BY base.created_at DESC, base.id DESC
`

type ListMovementsByUserIDAfterParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorMovementID pgtype.UUID        `json:"cursor_movement_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListMovementsByUserIDAfterRow struct {
	ID                pgtype.UUID        `json:"id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Description       string             `json:"description"`
	MovementTypeID    pgtype.UUID        `json:"movement_type_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	MovementTypeKey   string             `json:"movement_type_key"`
	MovementTypeName  string             `json:"movement_type_name"`
	CategoryName      string             `json:"category_name"`
	CategoryIsSystem  bool               `json:"category_is_system"`
	CategorySystemKey pgtype.Text        `json:"category_system_key"`
	AccountName       string             `json:"account_name"`
}

func (q *Queries) ListMovementsByUserIDAfter(ctx context.Context, arg ListMovementsByUserIDAfterParams) ([]ListMovementsByUserIDAfterRow, error) {
	rows, err := q.db.Query(ctx, listMovementsByUserIDAfter,
		arg.UserID,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorCreatedAt,
		arg.CursorMovementID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsByUserIDAfterRow{}
	for rows.Next() {
		var i ListMovementsByUserIDAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.MovementTypeID,
			&i.CategoryID,
			&i.AccountID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MovementTypeKey,
			&i.MovementTypeName,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.CategorySystemKey,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByUserIDAndAccountIDAfter = `-- name: ListMovementsByUserIDAndAccountIDAfter :many
WITH base AS (
  SELECT
    m.id,
    m.amount,
    m.description,
    m.movement_type_id,
    m.category_id,
    m.account_id,
    m.user_id,
    m.created_at,
    m.updated_at,
    m.deleted_at
  FROM movements m
  WHERE m.account_id = $1
    AND m.user_id = $2
    AND m.deleted_at IS NULL
    AND (
      $3::timestamptz IS NULL
      OR m.created_at >= $3::timestamptz
    )
    AND (
      $4::timestamptz IS NULL
      OR m.created_at <= $4::timestamptz
    )
    AND (
      $5::timestamptz IS NULL
      OR (m.created_at, m.id) < (
        $5::timestamptz,
        $6::uuid
      )
    )
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT $7
)
SELECT
  base.id,
  base.amount,
  base.description,
  base.movement_type_id,
  base.category_id,
  base.account_id,
  base.user_id,
  base.created_at,
  base.updated_at,
  base.deleted_at,
  mt.key AS movement_type_key,
  mt.name AS movement_type_name,
  c.name AS category_name,
  c.is_system AS category_is_system,
  c.system_key AS category_system_key,
  a.name AS account_name
FROM base
INNER JOIN movement_types mt
  ON mt.id = base.movement_type_id
 AND mt.deleted_at IS NULL
INNER JOIN categories c
  ON c.id = base.category_id
 AND c.deleted_at IS NULL
INNER JOIN accounts a
  ON a.id = base.account_id
 AND a.deleted_at IS NULL
ORDER BY base.created_at DESC, base.id DESC
`

type ListMovementsByUserIDAndAccountIDAfterParams struct {
	AccountID        pgtype.UUID        `json:"account_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorMovementID pgtype.UUID        `json:"cursor_movement_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListMovementsByUserIDAndAccountIDAfterRow struct {
	ID                pgtype.UUID        `json:"id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Description       string             `json:"description"`
	MovementTypeID    pgtype.UUID        `json:"movement_type_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	MovementTypeKey   string             `json:"movement_type_key"`
	MovementTypeName  string             `json:"movement_type_name"`
	CategoryName      string             `json:"category_name"`
	CategoryIsSystem  bool               `json:"category_is_system"`
	CategorySystemKey pgtype.Text        `json:"category_system_key"`
	AccountName       string             `json:"account_name"`
}

func (q *Queries) ListMovementsByUserIDAndAccountIDAfter(ctx context.Context, arg ListMovementsByUserIDAndAccountIDAfterParams) ([]ListMovementsByUserIDAndAccountIDAfterRow, error) {
	rows, err := q.db.Query(ctx, listMovementsByUserIDAndAccountIDAfter,
		arg.AccountID,
		arg.UserID,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorCreatedAt,
		arg.CursorMovementID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsByUserIDAndAccountIDAfterRow{}
	for rows.Next() {
		var i ListMovementsByUserIDAndAccountIDAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.MovementTypeID,
			&i.CategoryID,
			&i.AccountID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MovementTypeKey,
			&i.MovementTypeName,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.CategorySystemKey,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByUserIDAndAccountIDBefore = `-- name: ListMovementsByUserIDAndAccountIDBefore :many
WITH base AS (
  SELECT
    m.id,
    m.amount,
    m.description,
    m.movement_type_id,
    m.category_id,
    m.account_id,
    m.user_id,
    m.created_at,
    m.updated_at,
    m.deleted_at
  FROM movements m
  WHERE m.account_id = $1
    AND m.user_id = $2
    AND m.deleted_at IS NULL
    AND (
      $3::timestamptz IS NULL
      OR m.created_at >= $3::timestamptz
    )
    AND (
      $4::timestamptz IS NULL
      OR m.created_at <= $4::timestamptz
    )
    AND (m.created_at, m.id) > (
      $5::timestamptz,
      $6::uuid
    )
  ORDER BY m.created_at ASC, m.id ASC
  LIMIT $7
)
SELECT
  base.id,
  base.amount,
  base.description,
  base.movement_type_id,
  base.category_id,
  base.account_id,
  base.user_id,
  base.created_at,
  base.updated_at,
  base.deleted_at,
  mt.key AS movement_type_key,
  mt.name AS movement_type_name,
  c.name AS category_name,
  c.is_system AS category_is_system,
  c.system_key AS category_system_key,
  a.name AS account_name
FROM base
INNER JOIN movement_types mt
  ON mt.id = base.movement_type_id
 AND mt.deleted_at IS NULL
INNER JOIN categories c
  ON c.id = base.category_id
 AND c.deleted_at IS NULL
INNER JOIN accounts a
  ON a.id = base.account_id
 AND a.deleted_at IS NULL
ORDER BY base.created_at ASC, base.id ASC
`

type ListMovementsByUserIDAndAccountIDBeforeParams struct {
	AccountID        pgtype.UUID        `json:"account_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorMovementID pgtype.UUID        `json:"cursor_movement_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListMovementsByUserIDAndAccountIDBeforeRow struct {
	ID                pgtype.UUID        `json:"id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Description       string             `json:"description"`
	MovementTypeID    pgtype.UUID        `json:"movement_type_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	MovementTypeKey   string             `json:"movement_type_key"`
	MovementTypeName  string             `json:"movement_type_name"`
	CategoryName      string             `json:"category_name"`
	CategoryIsSystem  bool               `json:"category_is_system"`
	CategorySystemKey pgtype.Text        `json:"category_system_key"`
	AccountName       string             `json:"account_name"`
}

func (q *Queries) ListMovementsByUserIDAndAccountIDBefore(ctx context.Context, arg ListMovementsByUserIDAndAccountIDBeforeParams) ([]ListMovementsByUserIDAndAccountIDBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMovementsByUserIDAndAccountIDBefore,
		arg.AccountID,
		arg.UserID,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorCreatedAt,
		arg.CursorMovementID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsByUserIDAndAccountIDBeforeRow{}
	for rows.Next() {
		var i ListMovementsByUserIDAndAccountIDBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.MovementTypeID,
			&i.CategoryID,
			&i.AccountID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MovementTypeKey,
			&i.MovementTypeName,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.CategorySystemKey,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByUserIDAndCategoryIDAfter = `-- name: ListMovementsByUserIDAndCategoryIDAfter :many
WITH base AS (
  SELECT
    m.id,
    m.amount,
    m.description,
    m.movement_type_id,
    m.category_id,
    m.account_id,
    m.user_id,
    m.created_at,
    m.updated_at,
    m.deleted_at
  FROM movements m
  WHERE m.user_id = $1
    AND m.category_id = $2
    AND m.deleted_at IS NULL
    AND (
      $3::timestamptz IS NULL
      OR m.created_at >= $3::timestamptz
    )
    AND (
      $4::timestamptz IS NULL
      OR m.created_at <= $4::timestamptz
    )
    AND (
      $5::timestamptz IS NULL
      OR (m.created_at, m.id) < (
        $5::timestamptz,
        $6::uuid
      )
    )
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT $7
)
SELECT
  base.id,
  base.amount,
  base.description,
  base.movement_type_id,
  base.category_id,
  base.account_id,
  base.user_id,
  base.created_at,
  base.updated_at,
  base.deleted_at,
  mt.key AS movement_type_key,
  mt.name AS movement_type_name,
  c.name AS category_name,
  c.is_system AS category_is_system,
  c.system_key AS category_system_key,
  a.name AS account_name
FROM base
INNER JOIN movement_types mt
  ON mt.id = base.movement_type_id
 AND mt.deleted_at IS NULL
INNER JOIN categories c
  ON c.id = base.category_id
 AND c.deleted_at IS NULL
INNER JOIN accounts a
  ON a.id = base.account_id
 AND a.deleted_at IS NULL
ORDER BY base.created_at DESC, base.id DESC
`

type ListMovementsByUserIDAndCategoryIDAfterParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	CategoryID       pgtype.UUID        `json:"category_id"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorMovementID pgtype.UUID        `json:"cursor_movement_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListMovementsByUserIDAndCategoryIDAfterRow struct {
	ID                pgtype.UUID        `json:"id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Description       string             `json:"description"`
	MovementTypeID    pgtype.UUID        `json:"movement_type_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	MovementTypeKey   string             `json:"movement_type_key"`
	MovementTypeName  string             `json:"movement_type_name"`
	CategoryName      string             `json:"category_name"`
	CategoryIsSystem  bool               `json:"category_is_system"`
	CategorySystemKey pgtype.Text        `json:"category_system_key"`
	AccountName       string             `json:"account_name"`
}

func (q *Queries) ListMovementsByUserIDAndCategoryIDAfter(ctx context.Context, arg ListMovementsByUserIDAndCategoryIDAfterParams) ([]ListMovementsByUserIDAndCategoryIDAfterRow, error) {
	rows, err := q.db.Query(ctx, listMovementsByUserIDAndCategoryIDAfter,
		arg.UserID,
		arg.CategoryID,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorCreatedAt,
		arg.CursorMovementID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsByUserIDAndCategoryIDAfterRow{}
	for rows.Next() {
		var i ListMovementsByUserIDAndCategoryIDAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.MovementTypeID,
			&i.CategoryID,
			&i.AccountID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MovementTypeKey,
			&i.MovementTypeName,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.CategorySystemKey,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByUserIDAndCategoryIDBefore = `-- name: ListMovementsByUserIDAndCategoryIDBefore :many
WITH base AS (
  SELECT
    m.id,
    m.amount,
    m.description,
    m.movement_type_id,
    m.category_id,
    m.account_id,
    m.user_id,
    m.created_at,
    m.updated_at,
    m.deleted_at
  FROM movements m
  WHERE m.user_id = $1
    AND m.category_id = $2
    AND m.deleted_at IS NULL
    AND (
      $3::timestamptz IS NULL
      OR m.created_at >= $3::timestamptz
    )
    AND (
      $4::timestamptz IS NULL
      OR m.created_at <= $4::timestamptz
    )
    AND (m.created_at, m.id) > (
      $5::timestamptz,
      $6::uuid
    )
  ORDER BY m.created_at ASC, m.id ASC
  LIMIT $7
)
SELECT
  base.id,
  base.amount,
  base.description,
  base.movement_type_id,
  base.category_id,
  base.account_id,
  base.user_id,
  base.created_at,
  base.updated_at,
  base.deleted_at,
  mt.key AS movement_type_key,
  mt.name AS movement_type_name,
  c.name AS category_name,
  c.is_system AS category_is_system,
  c.system_key AS category_system_key,
  a.name AS account_name
FROM base
INNER JOIN movement_types mt
  ON mt.id = base.movement_type_id
 AND mt.deleted_at IS NULL
INNER JOIN categories c
  ON c.id = base.category_id
 AND c.deleted_at IS NULL
INNER JOIN accounts a
  ON a.id = base.account_id
 AND a.deleted_at IS NULL
ORDER BY base.created_at ASC, base.id ASC
`

type ListMovementsByUserIDAndCategoryIDBeforeParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	CategoryID       pgtype.UUID        `json:"category_id"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorMovementID pgtype.UUID        `json:"cursor_movement_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListMovementsByUserIDAndCategoryIDBeforeRow struct {
	ID                pgtype.UUID        `json:"id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Description       string             `json:"description"`
	MovementTypeID    pgtype.UUID        `json:"movement_type_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	MovementTypeKey   string             `json:"movement_type_key"`
	MovementTypeName  string             `json:"movement_type_name"`
	CategoryName      string             `json:"category_name"`
	CategoryIsSystem  bool               `json:"category_is_system"`
	CategorySystemKey pgtype.Text        `json:"category_system_key"`
	AccountName       string             `json:"account_name"`
}

func (q *Queries) ListMovementsByUserIDAndCategoryIDBefore(ctx context.Context, arg ListMovementsByUserIDAndCategoryIDBeforeParams) ([]ListMovementsByUserIDAndCategoryIDBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMovementsByUserIDAndCategoryIDBefore,
		arg.UserID,
		arg.CategoryID,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorCreatedAt,
		arg.CursorMovementID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsByUserIDAndCategoryIDBeforeRow{}
	for rows.Next() {
		var i ListMovementsByUserIDAndCategoryIDBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.MovementTypeID,
			&i.CategoryID,
			&i.AccountID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MovementTypeKey,
			&i.MovementTypeName,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.CategorySystemKey,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByUserIDAndMovementTypeIDAfter = `-- name: ListMovementsByUserIDAndMovementTypeIDAfter :many
WITH base AS (
  SELECT
    m.id,
    m.amount,
    m.description,
    m.movement_type_id,
    m.category_id,
    m.account_id,
    m.user_id,
    m.created_at,
    m.updated_at,
    m.deleted_at
  FROM movements m
  WHERE m.user_id = $1
    AND m.movement_type_id = $2
    AND m.deleted_at IS NULL
    AND (
      $3::timestamptz IS NULL
      OR m.created_at >= $3::timestamptz
    )
    AND (
      $4::timestamptz IS NULL
      OR m.created_at <= $4::timestamptz
    )
    AND (
      $5::timestamptz IS NULL
      OR (m.created_at, m.id) < (
        $5::timestamptz,
        $6::uuid
      )
    )
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT $7
)
SELECT
  base.id,
  base.amount,
  base.description,
  base.movement_type_id,
  base.category_id,
  base.account_id,
  base.user_id,
  base.created_at,
  base.updated_at,
  base.deleted_at,
  mt.key AS movement_type_key,
  mt.name AS movement_type_name,
  c.name AS category_name,
  c.is_system AS category_is_system,
  c.system_key AS category_system_key,
  a.name AS account_name
FROM base
INNER JOIN movement_types mt
  ON mt.id = base.movement_type_id
 AND mt.deleted_at IS NULL
INNER JOIN categories c
  ON c.id = base.category_id
 AND c.deleted_at IS NULL
INNER JOIN accounts a
  ON a.id = base.account_id
 AND a.deleted_at IS NULL
ORDER BY base.created_at DESC, base.id DESC
`

type ListMovementsByUserIDAndMovementTypeIDAfterParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	MovementTypeID   pgtype.UUID        `json:"movement_type_id"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorMovementID pgtype.UUID        `json:"cursor_movement_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListMovementsByUserIDAndMovementTypeIDAfterRow struct {
	ID                pgtype.UUID        `json:"id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Description       string             `json:"description"`
	MovementTypeID    pgtype.UUID        `json:"movement_type_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	MovementTypeKey   string             `json:"movement_type_key"`
	MovementTypeName  string             `json:"movement_type_name"`
	CategoryName      string             `json:"category_name"`
	CategoryIsSystem  bool               `json:"category_is_system"`
	CategorySystemKey pgtype.Text        `json:"category_system_key"`
	AccountName       string             `json:"account_name"`
}

func (q *Queries) ListMovementsByUserIDAndMovementTypeIDAfter(ctx context.Context, arg ListMovementsByUserIDAndMovementTypeIDAfterParams) ([]ListMovementsByUserIDAndMovementTypeIDAfterRow, error) {
	rows, err := q.db.Query(ctx, listMovementsByUserIDAndMovementTypeIDAfter,
		arg.UserID,
		arg.MovementTypeID,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorCreatedAt,
		arg.CursorMovementID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsByUserIDAndMovementTypeIDAfterRow{}
	for rows.Next() {
		var i ListMovementsByUserIDAndMovementTypeIDAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.MovementTypeID,
			&i.CategoryID,
			&i.AccountID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MovementTypeKey,
			&i.MovementTypeName,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.CategorySystemKey,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByUserIDAndMovementTypeIDBefore = `-- name: ListMovementsByUserIDAndMovementTypeIDBefore :many
WITH base AS (
  SELECT
    m.id,
    m.amount,
    m.description,
    m.movement_type_id,
    m.category_id,
    m.account_id,
    m.user_id,
    m.created_at,
    m.updated_at,
    m.deleted_at
  FROM movements m
  WHERE m.user_id = $1
    AND m.movement_type_id = $2
    AND m.deleted_at IS NULL
    AND (
      $3::timestamptz IS NULL
      OR m.created_at >= $3::timestamptz
    )
    AND (
      $4::timestamptz IS NULL
      OR m.created_at <= $4::timestamptz
    )
    AND (m.created_at, m.id) > (
      $5::timestamptz,
      $6::uuid
    )
  ORDER BY m.created_at ASC, m.id ASC
  LIMIT $7
)
SELECT
  base.id,
  base.amount,
  base.description,
  base.movement_type_id,
  base.category_id,
  base.account_id,
  base.user_id,
  base.created_at,
  base.updated_at,
  base.deleted_at,
  mt.key AS movement_type_key,
  mt.name AS movement_type_name,
  c.name AS category_name,
  c.is_system AS category_is_system,
  c.system_key AS category_system_key,
  a.name AS account_name
FROM base
INNER JOIN movement_types mt
  ON mt.id = base.movement_type_id
 AND mt.deleted_at IS NULL
INNER JOIN categories c
  ON c.id = base.category_id
 AND c.deleted_at IS NULL
INNER JOIN accounts a
  ON a.id = base.account_id
 AND a.deleted_at IS NULL
ORDER BY base.created_at ASC, base.id ASC
`

type ListMovementsByUserIDAndMovementTypeIDBeforeParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	MovementTypeID   pgtype.UUID        `json:"movement_type_id"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorMovementID pgtype.UUID        `json:"cursor_movement_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListMovementsByUserIDAndMovementTypeIDBeforeRow struct {
	ID                pgtype.UUID        `json:"id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Description       string             `json:"description"`
	MovementTypeID    pgtype.UUID        `json:"movement_type_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	MovementTypeKey   string             `json:"movement_type_key"`
	MovementTypeName  string             `json:"movement_type_name"`
	CategoryName      string             `json:"category_name"`
	CategoryIsSystem  bool               `json:"category_is_system"`
	CategorySystemKey pgtype.Text        `json:"category_system_key"`
	AccountName       string             `json:"account_name"`
}

func (q *Queries) ListMovementsByUserIDAndMovementTypeIDBefore(ctx context.Context, arg ListMovementsByUserIDAndMovementTypeIDBeforeParams) ([]ListMovementsByUserIDAndMovementTypeIDBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMovementsByUserIDAndMovementTypeIDBefore,
		arg.UserID,
		arg.MovementTypeID,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorCreatedAt,
		arg.CursorMovementID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsByUserIDAndMovementTypeIDBeforeRow{}
	for rows.Next() {
		var i ListMovementsByUserIDAndMovementTypeIDBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.MovementTypeID,
			&i.CategoryID,
			&i.AccountID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MovementTypeKey,
			&i.MovementTypeName,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.CategorySystemKey,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByUserIDBefore = `-- name: ListMovementsByUserIDBefore :many
WITH base AS (
  SELECT
    m.id,
    m.amount,
    m.description,
    m.movement_type_id,
    m.category_id,
    m.account_id,
    m.user_id,
    m.created_at,
    m.updated_at,
    m.deleted_at
  FROM movements m
  WHERE m.user_id = $1
    AND m.deleted_at IS NULL
    AND (
      $2::timestamptz IS NULL
      OR m.created_at >= $2::timestamptz
    )
    AND (
      $3::timestamptz IS NULL
      OR m.created_at <= $3::timestamptz
    )
    AND (m.created_at, m.id) > (
      $4::timestamptz,
      $5::uuid
    )
  ORDER BY m.created_at ASC, m.id ASC
  LIMIT $6
)
SELECT
  base.id,
  base.amount,
  base.description,
  base.movement_type_id,
  base.category_id,
  base.account_id,
  base.user_id,
  base.created_at,
  base.updated_at,
  base.deleted_at,
  mt.key AS movement_type_key,
  mt.name AS movement_type_name,
  c.name AS category_name,
  c.is_system AS category_is_system,
  c.system_key AS category_system_key,
  a.name AS account_name
FROM base
INNER JOIN movement_types mt
  ON mt.id = base.movement_type_id
 AND mt.deleted_at IS NULL
INNER JOIN categories c
  ON c.id = base.category_id
 AND c.deleted_at IS NULL
INNER JOIN accounts a
  ON a.id = base.account_id
 AND a.deleted_at IS NULL
ORDER BY base.created_at ASC, base.id ASC
`

type ListMovementsByUserIDBeforeParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorMovementID pgtype.UUID        `json:"cursor_movement_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListMovementsByUserIDBeforeRow struct {
	ID                pgtype.UUID        `json:"id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Description       string             `json:"description"`
	MovementTypeID    pgtype.UUID        `json:"movement_type_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	MovementTypeKey   string             `json:"movement_type_key"`
	MovementTypeName  string             `json:"movement_type_name"`
	CategoryName      string             `json:"category_name"`
	CategoryIsSystem  bool               `json:"category_is_system"`
	CategorySystemKey pgtype.Text        `json:"category_system_key"`
	AccountName       string             `json:"account_name"`
}

func (q *Queries) ListMovementsByUserIDBefore(ctx context.Context, arg ListMovementsByUserIDBeforeParams) ([]ListMovementsByUserIDBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMovementsByUserIDBefore,
		arg.UserID,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorCreatedAt,
		arg.CursorMovementID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsByUserIDBeforeRow{}
	for rows.Next() {
		var i ListMovementsByUserIDBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.MovementTypeID,
			&i.CategoryID,
			&i.AccountID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MovementTypeKey,
			&i.MovementTypeName,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.CategorySystemKey,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByUserIDFilteredAfter = `-- name: ListMovementsByUserIDFilteredAfter :many
WITH base AS (
  SELECT
    m.id,
    m.amount,
    m.description,
    m.movement_type_id,
    m.category_id,
    m.account_id,
    m.user_id,
    m.created_at,
    m.updated_at,
    m.deleted_at
  FROM movements m
  WHERE m.user_id = $1
    AND m.deleted_at IS NULL
    AND (
      $2::uuid IS NULL
      OR m.account_id = $2::uuid
    )
    AND (
      $3::uuid IS NULL
      OR m.category_id = $3::uuid
    )
    AND (
      $4::uuid IS NULL
      OR m.movement_type_id = $4::uuid
    )
    AND (
      $5::timestamptz IS NULL
      OR m.created_at >= $5::timestamptz
    )
    AND (
      $6::timestamptz IS NULL
      OR m.created_at <= $6::timestamptz
    )
    AND (
      $7::timestamptz IS NULL
      OR (m.created_at, m.id) < (
        $7::timestamptz,
        $8::uuid
      )
    )
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT $9
)
SELECT
  base.id,
  base.amount,
  base.description,
  base.movement_type_id,
  base.category_id,
  base.account_id,
  base.user_id,
  base.created_at,
  base.updated_at,
  base.deleted_at,
  mt.key AS movement_type_key,
  mt.name AS movement_type_name,
  c.name AS category_name,
  c.is_system AS category_is_system,
  c.system_key AS category_system_key,
  a.name AS account_name
FROM base
INNER JOIN movement_types mt
  ON mt.id = base.movement_type_id
 AND mt.deleted_at IS NULL
INNER JOIN categories c
  ON c.id = base.category_id
 AND c.deleted_at IS NULL
INNER JOIN accounts a
  ON a.id = base.account_id
 AND a.deleted_at IS NULL
ORDER BY base.created_at DESC, base.id DESC
`

type ListMovementsByUserIDFilteredAfterParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	AccountID        pgtype.UUID        `json:"account_id"`
	CategoryID       pgtype.UUID        `json:"category_id"`
	MovementTypeID   pgtype.UUID        `json:"movement_type_id"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorMovementID pgtype.UUID        `json:"cursor_movement_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListMovementsByUserIDFilteredAfterRow struct {
	ID                pgtype.UUID        `json:"id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Description       string             `json:"description"`
	MovementTypeID    pgtype.UUID        `json:"movement_type_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	MovementTypeKey   string             `json:"movement_type_key"`
	MovementTypeName  string             `json:"movement_type_name"`
	CategoryName      string             `json:"category_name"`
	CategoryIsSystem  bool               `json:"category_is_system"`
	CategorySystemKey pgtype.Text        `json:"category_system_key"`
	AccountName       string             `json:"account_name"`
}

func (q *Queries) ListMovementsByUserIDFilteredAfter(ctx context.Context, arg ListMovementsByUserIDFilteredAfterParams) ([]ListMovementsByUserIDFilteredAfterRow, error) {
	rows, err := q.db.Query(ctx, listMovementsByUserIDFilteredAfter,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.MovementTypeID,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorCreatedAt,
		arg.CursorMovementID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsByUserIDFilteredAfterRow{}
	for rows.Next() {
		var i ListMovementsByUserIDFilteredAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.MovementTypeID,
			&i.CategoryID,
			&i.AccountID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MovementTypeKey,
			&i.MovementTypeName,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.CategorySystemKey,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByUserIDFilteredBefore = `-- name: ListMovementsByUserIDFilteredBefore :many
WITH base AS (
  SELECT
    m.id,
    m.amount,
    m.description,
    m.movement_type_id,
    m.category_id,
    m.account_id,
    m.user_id,
    m.created_at,
    m.updated_at,
    m.deleted_at
  FROM movements m
  WHERE m.user_id = $1
    AND m.deleted_at IS NULL
    AND (
      $2::uuid IS NULL
      OR m.account_id = $2::uuid
    )
    AND (
      $3::uuid IS NULL
      OR m.category_id = $3::uuid
    )
    AND (
      $4::uuid IS NULL
      OR m.movement_type_id = $4::uuid
    )
    AND (
      $5::timestamptz IS NULL
      OR m.created_at >= $5::timestamptz
    )
    AND (
      $6::timestamptz IS NULL
      OR m.created_at <= $6::timestamptz
    )
    AND (m.created_at, m.id) > (
      $7::timestamptz,
      $8::uuid
    )
  ORDER BY m.created_at ASC, m.id ASC
  LIMIT $9
)
SELECT
  base.id,
  base.amount,
  base.description,
  base.movement_type_id,
  base.category_id,
  base.account_id,
  base.user_id,
  base.created_at,
  base.updated_at,
  base.deleted_at,
  mt.key AS movement_type_key,
  mt.name AS movement_type_name,
  c.name AS category_name,
  c.is_system AS category_is_system,
  c.system_key AS category_system_key,
  a.name AS account_name
FROM base
INNER JOIN movement_types mt
  ON mt.id = base.movement_type_id
 AND mt.deleted_at IS NULL
INNER JOIN categories c
  ON c.id = base.category_id
 AND c.deleted_at IS NULL
INNER JOIN accounts a
  ON a.id = base.account_id
 AND a.deleted_at IS NULL
ORDER BY base.created_at ASC, base.id ASC
`

type ListMovementsByUserIDFilteredBeforeParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	AccountID        pgtype.UUID        `json:"account_id"`
	CategoryID       pgtype.UUID        `json:"category_id"`
	MovementTypeID   pgtype.UUID        `json:"movement_type_id"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
	CursorCreatedAt  pgtype.Timestamptz `json:"cursor_created_at"`
	CursorMovementID pgtype.UUID        `json:"cursor_movement_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListMovementsByUserIDFilteredBeforeRow struct {
	ID                pgtype.UUID        `json:"id"`
	Amount            pgtype.Numeric     `json:"amount"`
	Description       string             `json:"description"`
	MovementTypeID    pgtype.UUID        `json:"movement_type_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	MovementTypeKey   string             `json:"movement_type_key"`
	MovementTypeName  string             `json:"movement_type_name"`
	CategoryName      string             `json:"category_name"`
	CategoryIsSystem  bool               `json:"category_is_system"`
	CategorySystemKey pgtype.Text        `json:"category_system_key"`
	AccountName       string             `json:"account_name"`
}

func (q *Queries) ListMovementsByUserIDFilteredBefore(ctx context.Context, arg ListMovementsByUserIDFilteredBeforeParams) ([]ListMovementsByUserIDFilteredBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMovementsByUserIDFilteredBefore,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.MovementTypeID,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorCreatedAt,
		arg.CursorMovementID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsByUserIDFilteredBeforeRow{}
	for rows.Next() {
		var i ListMovementsByUserIDFilteredBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.MovementTypeID,
			&i.CategoryID,
			&i.AccountID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MovementTypeKey,
			&i.MovementTypeName,
			&i.CategoryName,
			&i.CategoryIsSystem,
			&i.CategorySystemKey,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
