// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: references.sql

package movementdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountExistsByUserID = `-- name: AccountExistsByUserID :one
SELECT EXISTS (
  SELECT 1
  FROM accounts
  WHERE id = $1
    AND user_id = $2
    AND deleted_at IS NULL
)
`

type AccountExistsByUserIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AccountExistsByUserID(ctx context.Context, arg AccountExistsByUserIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, accountExistsByUserID, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const decreaseAccountBalance = `-- name: DecreaseAccountBalance :execrows
UPDATE accounts
SET
  balance = balance - $1,
  updated_at = $4
WHERE id = $2
  AND user_id = $3
  AND deleted_at IS NULL
  AND balance >= $1
`

type DecreaseAccountBalanceParams struct {
	Balance   pgtype.Numeric     `json:"balance"`
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DecreaseAccountBalance(ctx context.Context, arg DecreaseAccountBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, decreaseAccountBalance,
		arg.Balance,
		arg.ID,
		arg.UserID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT
  id,
  name,
  created_at,
  updated_at,
  deleted_at
FROM categories
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMovementTypeByID = `-- name: GetMovementTypeByID :one
SELECT
  id,
  name,
  key,
  description,
  created_at,
  updated_at,
  deleted_at
FROM movement_types
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetMovementTypeByID(ctx context.Context, id pgtype.UUID) (MovementType, error) {
	row := q.db.QueryRow(ctx, getMovementTypeByID, id)
	var i MovementType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const increaseAccountBalance = `-- name: IncreaseAccountBalance :execrows
UPDATE accounts
SET
  balance = balance + $1,
  updated_at = $4
WHERE id = $2
  AND user_id = $3
  AND deleted_at IS NULL
`

type IncreaseAccountBalanceParams struct {
	Balance   pgtype.Numeric     `json:"balance"`
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) IncreaseAccountBalance(ctx context.Context, arg IncreaseAccountBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, increaseAccountBalance,
		arg.Balance,
		arg.ID,
		arg.UserID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
  SELECT 1
  FROM users
  WHERE id = $1
    AND deleted_at IS NULL
)
`

func (q *Queries) UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
