// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: references.sql

package movementdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountExistsByUserID = `-- name: AccountExistsByUserID :one
SELECT EXISTS (
  SELECT 1
  FROM accounts
  WHERE id = $1
    AND user_id = $2
    AND deleted_at IS NULL
)
`

type AccountExistsByUserIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AccountExistsByUserID(ctx context.Context, arg AccountExistsByUserIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, accountExistsByUserID, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const decreaseAccountBalance = `-- name: DecreaseAccountBalance :execrows
UPDATE accounts
SET
  balance = balance - $1,
  updated_at = $4
WHERE id = $2
  AND user_id = $3
  AND deleted_at IS NULL
  AND balance >= $1
`

type DecreaseAccountBalanceParams struct {
	Balance   pgtype.Numeric     `json:"balance"`
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DecreaseAccountBalance(ctx context.Context, arg DecreaseAccountBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, decreaseAccountBalance,
		arg.Balance,
		arg.ID,
		arg.UserID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategoryByIDForUser = `-- name: GetCategoryByIDForUser :one
SELECT
  c.id,
  c.name,
  c.is_system,
  c.system_key
FROM user_categories uc
INNER JOIN categories c
  ON c.id = uc.category_id
 AND c.deleted_at IS NULL
WHERE uc.category_id = $1
  AND uc.user_id = $2
  AND uc.deleted_at IS NULL
  AND c.is_system = FALSE
`

type GetCategoryByIDForUserParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

type GetCategoryByIDForUserRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	IsSystem  bool        `json:"is_system"`
	SystemKey pgtype.Text `json:"system_key"`
}

func (q *Queries) GetCategoryByIDForUser(ctx context.Context, arg GetCategoryByIDForUserParams) (GetCategoryByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByIDForUser, arg.CategoryID, arg.UserID)
	var i GetCategoryByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSystem,
		&i.SystemKey,
	)
	return i, err
}

const getMovementTypeByID = `-- name: GetMovementTypeByID :one
SELECT
  id,
  name,
  key,
  description,
  created_at,
  updated_at,
  deleted_at
FROM movement_types
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetMovementTypeByID(ctx context.Context, id pgtype.UUID) (MovementType, error) {
	row := q.db.QueryRow(ctx, getMovementTypeByID, id)
	var i MovementType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const increaseAccountBalance = `-- name: IncreaseAccountBalance :execrows
UPDATE accounts
SET
  balance = balance + $1,
  updated_at = $4
WHERE id = $2
  AND user_id = $3
  AND deleted_at IS NULL
`

type IncreaseAccountBalanceParams struct {
	Balance   pgtype.Numeric     `json:"balance"`
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) IncreaseAccountBalance(ctx context.Context, arg IncreaseAccountBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, increaseAccountBalance,
		arg.Balance,
		arg.ID,
		arg.UserID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMovementTypes = `-- name: ListMovementTypes :many
SELECT
  id,
  name,
  key,
  description,
  created_at,
  updated_at,
  deleted_at
FROM movement_types
WHERE deleted_at IS NULL
ORDER BY key ASC, id ASC
`

func (q *Queries) ListMovementTypes(ctx context.Context) ([]MovementType, error) {
	rows, err := q.db.Query(ctx, listMovementTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MovementType{}
	for rows.Next() {
		var i MovementType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
  SELECT 1
  FROM users
  WHERE id = $1
    AND deleted_at IS NULL
)
`

func (q *Queries) UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
