apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://expense-control-prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://expense-control-loki:3100

  - name: Tempo
    type: tempo
    access: proxy
    url: http://expense-control-tempo:3200
