// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO auth_sessions (
  id,
  user_id,
  refresh_jti,
  created_at,
  expires_at,
  revoked_at
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RefreshJti pgtype.UUID        `json:"refresh_jti"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshJti,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
  id,
  user_id,
  refresh_jti,
  created_at,
  expires_at,
  revoked_at
FROM auth_sessions
WHERE id = $1
AND revoked_at IS NULL
AND expires_at > NOW()
`

type GetSessionByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RefreshJti pgtype.UUID        `json:"refresh_jti"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshJti,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions
SET
  revoked_at = $2
WHERE id = $1
AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt)
	return err
}

const rotateSessionRefreshID = `-- name: RotateSessionRefreshID :execrows
UPDATE auth_sessions
SET
  refresh_jti = $2,
  expires_at = $3
WHERE id = $1
AND refresh_jti = $4
AND revoked_at IS NULL
AND expires_at > NOW()
`

type RotateSessionRefreshIDParams struct {
	ID           pgtype.UUID        `json:"id"`
	RefreshJti   pgtype.UUID        `json:"refresh_jti"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RefreshJti_2 pgtype.UUID        `json:"refresh_jti_2"`
}

func (q *Queries) RotateSessionRefreshID(ctx context.Context, arg RotateSessionRefreshIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSessionRefreshID,
		arg.ID,
		arg.RefreshJti,
		arg.ExpiresAt,
		arg.RefreshJti_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
