// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions (
  id,
  user_id,
  refresh_jti,
  created_at,
  expires_at,
  revoked_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
  id,
  user_id,
  refresh_jti,
  created_at,
  expires_at,
  revoked_at
`

type CreateSessionParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RefreshJti pgtype.UUID        `json:"refresh_jti"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type CreateSessionRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RefreshJti pgtype.UUID        `json:"refresh_jti"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshJti,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshJti,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
  id,
  user_id,
  refresh_jti,
  created_at,
  expires_at,
  revoked_at
FROM auth_sessions
WHERE id = $1
AND revoked_at IS NULL
`

type GetSessionByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RefreshJti pgtype.UUID        `json:"refresh_jti"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshJti,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE auth_sessions
SET
  revoked_at = $2
WHERE id = $1
AND revoked_at IS NULL
RETURNING
  id,
  user_id,
  refresh_jti,
  created_at,
  expires_at,
  revoked_at
`

type RevokeSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type RevokeSessionRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RefreshJti pgtype.UUID        `json:"refresh_jti"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (RevokeSessionRow, error) {
	row := q.db.QueryRow(ctx, revokeSession, arg.ID, arg.RevokedAt)
	var i RevokeSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshJti,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const rotateSessionRefreshID = `-- name: RotateSessionRefreshID :one
UPDATE auth_sessions
SET
  refresh_jti = $2,
  expires_at = $3
WHERE id = $1
AND revoked_at IS NULL
RETURNING
  id,
  user_id,
  refresh_jti,
  created_at,
  expires_at,
  revoked_at
`

type RotateSessionRefreshIDParams struct {
	ID         pgtype.UUID        `json:"id"`
	RefreshJti pgtype.UUID        `json:"refresh_jti"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type RotateSessionRefreshIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RefreshJti pgtype.UUID        `json:"refresh_jti"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RotateSessionRefreshID(ctx context.Context, arg RotateSessionRefreshIDParams) (RotateSessionRefreshIDRow, error) {
	row := q.db.QueryRow(ctx, rotateSessionRefreshID, arg.ID, arg.RefreshJti, arg.ExpiresAt)
	var i RotateSessionRefreshIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshJti,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
