// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package accountdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (
  id,
  name,
  balance,
  user_id,
  created_at,
  updated_at,
  deleted_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAccountParams struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Balance   pgtype.Numeric     `json:"balance"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.Balance,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE accounts
SET
  deleted_at = $2,
  updated_at = $3
WHERE id = $1
AND deleted_at IS NULL
`

type DeleteAccountParams struct {
	ID        pgtype.UUID        `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.DeletedAt, arg.UpdatedAt)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT
  id,
  name,
  balance,
  user_id,
  created_at,
  updated_at,
  deleted_at
FROM accounts
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountsByUserID = `-- name: ListAccountsByUserID :many
SELECT
  id,
  name,
  balance,
  user_id,
  created_at,
  updated_at,
  deleted_at
FROM accounts
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::timestamptz IS NULL OR (created_at, id) < ($2, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAccountsByUserIDParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.UUID        `json:"column_3"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) ListAccountsByUserID(ctx context.Context, arg ListAccountsByUserIDParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUserID,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Balance,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET
  balance = $2,
  updated_at = $3
WHERE id = $1
AND deleted_at IS NULL
`

type UpdateAccountBalanceParams struct {
	ID        pgtype.UUID        `json:"id"`
	Balance   pgtype.Numeric     `json:"balance"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.ID, arg.Balance, arg.UpdatedAt)
	return err
}

const updateAccountName = `-- name: UpdateAccountName :exec
UPDATE accounts
SET
  name = $2,
  updated_at = $3
WHERE id = $1
AND deleted_at IS NULL
`

type UpdateAccountNameParams struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAccountName(ctx context.Context, arg UpdateAccountNameParams) error {
	_, err := q.db.Exec(ctx, updateAccountName, arg.ID, arg.Name, arg.UpdatedAt)
	return err
}
