// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: initial_balance.sql

package accountdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInitialBalanceMovement = `-- name: CreateInitialBalanceMovement :exec
INSERT INTO movements (
  id,
  amount,
  description,
  movement_type_id,
  category_id,
  account_id,
  user_id,
  created_at,
  updated_at,
  deleted_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
`

type CreateInitialBalanceMovementParams struct {
	ID             pgtype.UUID        `json:"id"`
	Amount         pgtype.Numeric     `json:"amount"`
	Description    string             `json:"description"`
	MovementTypeID pgtype.UUID        `json:"movement_type_id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateInitialBalanceMovement(ctx context.Context, arg CreateInitialBalanceMovementParams) error {
	_, err := q.db.Exec(ctx, createInitialBalanceMovement,
		arg.ID,
		arg.Amount,
		arg.Description,
		arg.MovementTypeID,
		arg.CategoryID,
		arg.AccountID,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const getMovementTypeIDByKey = `-- name: GetMovementTypeIDByKey :one
SELECT id
FROM movement_types
WHERE key = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetMovementTypeIDByKey(ctx context.Context, key string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMovementTypeIDByKey, key)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertSystemCategoryByKey = `-- name: UpsertSystemCategoryByKey :one
INSERT INTO categories (
  id,
  name,
  is_system,
  system_key,
  created_at,
  updated_at,
  deleted_at
)
VALUES (
  $1,
  $2,
  TRUE,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (system_key) WHERE system_key IS NOT NULL DO UPDATE
SET
  name = EXCLUDED.name,
  deleted_at = NULL,
  updated_at = EXCLUDED.updated_at
RETURNING id
`

type UpsertSystemCategoryByKeyParams struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	SystemKey pgtype.Text        `json:"system_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpsertSystemCategoryByKey(ctx context.Context, arg UpsertSystemCategoryByKeyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSystemCategoryByKey,
		arg.ID,
		arg.Name,
		arg.SystemKey,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertUserCategory = `-- name: UpsertUserCategory :one
INSERT INTO user_categories (
  user_id,
  category_id,
  created_at,
  updated_at,
  deleted_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
ON CONFLICT (user_id, category_id) DO UPDATE
SET
  updated_at = CASE
    WHEN user_categories.deleted_at IS NULL THEN user_categories.updated_at
    ELSE EXCLUDED.updated_at
  END,
  deleted_at = NULL
RETURNING user_id, category_id, created_at, updated_at
`

type UpsertUserCategoryParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type UpsertUserCategoryRow struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertUserCategory(ctx context.Context, arg UpsertUserCategoryParams) (UpsertUserCategoryRow, error) {
	row := q.db.QueryRow(ctx, upsertUserCategory,
		arg.UserID,
		arg.CategoryID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i UpsertUserCategoryRow
	err := row.Scan(
		&i.UserID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
