services:
  expense-control-back:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    container_name: expense-control-back
    environment:
      TZ: America/Hermosillo
    volumes:
      - ../:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - expense-control-back-network
    depends_on:
      - expense-control-otel-collector

  expense-control-back-db:
    image: postgres:17.6
    container_name: expense-control-back-db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: expense-control-back
      TZ: America/Hermosillo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - expense-control-back-network

  expense-control-back-adminer:
    image: adminer
    container_name: expense-control-back-adminer
    environment:
      TZ: America/Hermosillo
      ADMINER_DESIGN: "ng9"
    ports:
      - 8080:8080
    depends_on:
      expense-control-back-db:
        condition: service_started
    networks:
      - expense-control-back-network

  expense-control-grafana:
    image: grafana/grafana:main-ubuntu
    container_name: expense-control-grafana
    ports:
      - 3000:3000
    networks:
      - expense-control-back-network
    volumes:
      - ../observability/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana

  expense-control-prometheus:
    image: prom/prometheus:latest
    container_name: expense-control-prometheus
    ports:
      - 9090:9090
    networks:
      - expense-control-back-network
    volumes:
      - ../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  expense-control-loki:
    image: grafana/loki:2.9.8
    container_name: expense-control-loki
    ports:
      - 3100:3100
    networks:
      - expense-control-back-network
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ../observability/loki/config.yml:/etc/loki/config.yml
      - loki_data:/loki

  expense-control-tempo:
    image: grafana/tempo:2.4.1
    container_name: expense-control-tempo
    ports:
      - 3200:3200
    networks:
      - expense-control-back-network
    command: ["-config.file=/etc/tempo/config.yml"]
    volumes:
      - ../observability/tempo/config.yml:/etc/tempo/config.yml
      - tempo_data:/tmp/tempo

  expense-control-otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: expense-control-otel-collector
    networks:
      - expense-control-back-network
    ports:
      - 8888:8888
    command: ["--config=/etc/otelcol/config.yml"]
    volumes:
      - ../observability/otel-collector/config.yml:/etc/otelcol/config.yml
    depends_on:
      - expense-control-tempo

  expense-control-promtail:
    image: grafana/promtail:2.9.8
    container_name: expense-control-promtail
    networks:
      - expense-control-back-network
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../observability/promtail/config.yml:/etc/promtail/config.yml
      - promtail_data:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - expense-control-loki

networks:
  expense-control-back-network:
    driver: bridge

volumes:
  pgdata:
  loki_data:
  tempo_data:
  prometheus_data:
  grafana_data:
  promtail_data: